syntax = "proto3";

package books;

option go_package = "/bookspb";

import "google/protobuf/timestamp.proto";

service BookService {
  rpc GetAllBooks (EmptyRequest) returns (BookList);
  rpc GetBookByTitle (BookTitleRequest) returns (Book);
  rpc GetBookByID (BookIDRequest) returns (Book);
  rpc CreateBook (Book) returns (SimpleResponse);
  rpc DeleteBook (Book) returns (SimpleResponse);
  rpc CheckCopiesOfBookByID (BookIDRequest) returns (SimpleResponse);
  rpc CheckCopiesOfBook (Book) returns (SimpleResponse);
  rpc MinusCopyOfBookById (BookIDRequest) returns (SimpleResponse);
  rpc PlusCopyOfBookById (BookIDRequest) returns (SimpleResponse);
}

message EmptyRequest {}

message SimpleResponse {
  string result = 1;
}

message Book {
  int32 id = 1;
  string title = 2;
  int32 copies = 3;
  string author = 4;
  google.protobuf.Timestamp issue = 5;
}

message BookList {
  repeated Book books = 1;
}

message BookTitleRequest {
  string title = 1;
}

message BookIDRequest {
  int32 id = 1;
}