syntax = "proto3";

package library.v1;
option go_package = "goproject/protos/gen";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "protos/proto/annotations.proto";

message Book {
  int32 ID = 1;
  string title = 2;
  int32 copies = 3;
  string author = 4;
  google.protobuf.Timestamp issue = 5;
}

message Reader {
  int32 ID = 1;
  string name = 2;
  string phone_number = 3;
  string address = 4;
  google.protobuf.Timestamp date_of_birth = 5;
}

message BookInUse {
  Book book_info = 1;
  google.protobuf.Timestamp date_of_rent = 2;
}

message Error {
  string message = 1;
  string error = 2;
}

message BookIdRequest {
  int32 id = 1;
}

message BookTitleRequest {
  string title = 1;
}

message ReaderIdRequest {
  int32 reader_id = 1;
}

message ReaderNameRequest {
  string name = 1;
}

message CreateBookRequest {
  Book book = 1;
}

message CreateReaderRequest {
  Reader reader = 1;
}

message BookInUseIdRequest {
  int32 book_id = 1;
  int32 reader_id = 2;
}

message RentOrReturnBookRequest {
  string name = 1;
  string title = 2;
}

message CountResponse {
  int32 count = 1;
}

message IdResponse {
  int32 id = 1;
}

message MessageResponse {
  string message = 1;
}

message BooksResponse {
  repeated Book books = 1;
}

message ReadersResponse {
  repeated Reader readers = 1;
}

message BooksInUseResponse {
  repeated BookInUse books_in_use = 1;
}

message ReaderIdsResponse {
  repeated int32 reader_ids = 1;
}

message ReadersBooksResponse {
  repeated BookInUse ok_books = 1;
  repeated BookInUse bad_books = 2;
}

service Library {
  // Books
  rpc GetAllBooks(google.protobuf.Empty) returns (BooksResponse) {
    option (google.api.http) = {
      get: "/books"
    };
  }

  rpc GetBookByTitle(BookTitleRequest) returns (Book) {
    option (google.api.http) = {
      post: "/book/title"
      body: "*"
    };
  }

  rpc GetBookIdByTitle(BookTitleRequest) returns (IdResponse) {
    option (google.api.http) = {
      post: "/book/id/title"
      body: "*"
    };
  }

  rpc GetBookByID(BookIdRequest) returns (Book) {
    option (google.api.http) = {
      post: "/book/id"
      body: "*"
    };
  }

  rpc CreateBook(CreateBookRequest) returns (MessageResponse) {
    option (google.api.http) = {
      post: "/book"
      body: "*"
    };
  }

  rpc DeleteBook(BookIdRequest) returns (MessageResponse) {
    option (google.api.http) = {
      delete: "/book"
      body: "id"
    };
  }

  rpc CheckCopiesOfBookByID(BookIdRequest) returns (MessageResponse) {
    option (google.api.http) = {
      post: "/book/check/id"
      body: "*"
    };
  }

  rpc SubtractCopyOfBookById(BookIdRequest) returns (MessageResponse) {
    option (google.api.http) = {
      patch: "/book/minus"
      body: "*"
    };
  }

  rpc AddCopyOfBookById(BookIdRequest) returns (MessageResponse) {
    option (google.api.http) = {
      patch: "/book/plus"
      body: "*"
    };
  }

  // Readers
  rpc GetAllReaders(google.protobuf.Empty) returns (ReadersResponse) {
    option (google.api.http) = {
      get: "/readers"
    };
  }

  rpc GetReaderIdByName(ReaderNameRequest) returns (IdResponse) {
    option (google.api.http) = {
      post: "/reader/id"
      body: "name"
    };
  }

  rpc CreateReader(CreateReaderRequest) returns (MessageResponse) {
    option (google.api.http) = {
      post: "/reader"
      body: "*"
    };
  }

  rpc DeleteReader(ReaderIdRequest) returns (MessageResponse) {
    option (google.api.http) = {
      delete: "/reader"
      body: "reader_id"
    };
  }

  rpc UpdateReaderContactInfo(Reader) returns (MessageResponse) {
    option (google.api.http) = {
      patch: "/reader/contact"
      body: "*"
    };
  }

  // Rentals (InUse)
  rpc CreateBookInUse(BookInUseIdRequest) returns (MessageResponse) {
    option (google.api.http) = {
      post: "/reader/book"
      body: "*"
    };
  }

  rpc GetAllBooksInUse(google.protobuf.Empty) returns (BooksInUseResponse) {
    option (google.api.http) = {
      get: "/reader/book"
    };
  }

  rpc CountBookInUseByReaderId(ReaderIdRequest) returns (CountResponse) {
    option (google.api.http) = {
      post: "/reader/book/count"
      body: "reader_id"
    };
  }

  rpc GetBooksInUseByReaderId(ReaderIdRequest) returns (BooksInUseResponse) {
    option (google.api.http) = {
      post: "/reader/book/id"
      body: "reader_id"
    };
  }

  rpc DeleteBookInUse(BookInUseIdRequest) returns (MessageResponse) {
    option (google.api.http) = {
      delete: "/reader/book"
      body: "*"
    };
  }

  rpc RentBookByTitleAndReaderName(RentOrReturnBookRequest) returns (MessageResponse) {
    option (google.api.http) = {
      patch: "/rent"
      body: "*"
    };
  }

  rpc ReturnBookByTitleAndReaderName(RentOrReturnBookRequest) returns (MessageResponse) {
    option (google.api.http) = {
      patch: "/return"
      body: "*"
    };
  }

  rpc GetReadersIdsByBookId(BookIdRequest) returns (ReaderIdsResponse) {
    option (google.api.http) = {
      post: "/reader/id/book"
      body: "id"
    };
  }

  rpc GetReaderBooksSepGoodAndBad(ReaderNameRequest) returns (ReadersBooksResponse) {
    option (google.api.http) = {
      post: "/reader/books"
      body: "name"
    };
  }
}
